name: s2s
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pkgs/main::python=3.8
  - bioconda::snakemake=5.30.1
  - pkgs/main::conda=4.9.2
  - conda-forge::mamba=0.7.1
  - bioconda::genomepy=0.9.1
  - anaconda::biopython=1.74
  - pkgs/main::filelock=3.0.12
  - pkgs/main::pyyaml=5.3.1
  - conda-forge::pandas_schema=0.3.5
  - bioconda::trackhub=0.1.2019.12.24
  - bioconda::pysradb=0.11.1
  - conda-forge::matplotlib=3.3.2
  - conda-forge::xdg=5.0.1
