name: s2s
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.8
  - bioconda::snakemake-minimal=7.25.0
  - conda-forge::conda=23.1.0
  - conda-forge::mamba=1.2.0
  - bioconda::genomepy=0.15.0
  - conda-forge::biopython=1.79
  - conda-forge::filelock=3.7.1
  - conda-forge::pyyaml=6.0
  - conda-forge::pandas_schema=0.3.5
  - conda-forge::pandas=1.3.2
  - bioconda::trackhub=0.1.2019.12.24
  - bioconda::pysradb=1.4.2
  - conda-forge::matplotlib=3.5.2
  - conda-forge::xdg=5.1.1
  - conda-forge::argcomplete=2.0.0
  - conda-forge::tabulate=0.9.0
  - conda-forge::conda-ecosystem-user-package-isolation=1.0
