name: s2s
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.10
  - bioconda::snakemake-minimal=7.25.0
  - conda-forge::conda=24.1.2
  - conda-forge::mamba=1.5.9
  - bioconda::genomepy=0.16.2
  - conda-forge::biopython=1.81
  - conda-forge::filelock=3.10.7
  - conda-forge::pyyaml=6.0
  - conda-forge::pandas_schema=0.3.5
  - conda-forge::pandas=1.5.3
  - bioconda::trackhub=0.1.2019.12.24
  - bioconda::pysradb=2.0.1
  - conda-forge::matplotlib-base=3.7.1
  - conda-forge::xdg=6.0.0
  - conda-forge::argcomplete=3.0.5
  - conda-forge::tabulate=0.9.0
  - conda-forge::conda-ecosystem-user-package-isolation=1.0
