name: s2s
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.8
  - bioconda::snakemake-minimal==6.12.0
  - conda-forge::conda=4.11.0
  - conda-forge::mamba=0.19.0
  - bioconda::genomepy=0.11.0
  - conda-forge::biopython=1.79
  - conda-forge::filelock=3.4.0
  - conda-forge::pyyaml=6.0
  - conda-forge::pandas_schema=0.3.5
  - bioconda::trackhub=0.1.2019.12.24
  - bioconda::pysradb=1.0.1
  - conda-forge::matplotlib=3.5.0
  - conda-forge::xdg=5.1.1
  - conda-forge::argcomplete=1.12.3
