name: s2s
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.8
  - bioconda::snakemake-minimal=7.7.0
  - conda-forge::conda=4.11.0
  - conda-forge::mamba=0.23.3
  - bioconda::genomepy=0.12.0
  - conda-forge::biopython=1.79
  - conda-forge::filelock=3.4.0
  - conda-forge::pyyaml=6.0
  - conda-forge::pandas_schema=0.3.5
  - conda-forge::pandas=1.3.2
  - bioconda::trackhub=0.1.2019.12.24
  - bioconda::pysradb=1.4.1
  - conda-forge::matplotlib=3.5.0
  - conda-forge::xdg=5.1.1
  - conda-forge::argcomplete=1.12.3
  - conda-forge::tabulate=0.8.9
  - conda-forge::conda-ecosystem-user-package-isolation=1.0
