name: s2s
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pkgs/main::python=3.6
  - bioconda::snakemake=5.18.1
  - bioconda::genomepy=0.9.1
  - bioconda::pysam=0.15.3
  - pkgs/main::conda=4.8.4
  - anaconda::biopython=1.74
  - pkgs/main::filelock=3.0.12
  - pkgs/main::pyyaml=5.3.1
  - conda-forge::pretty_html_table=0.9.dev0
  - conda-forge::pandas_schema=0.3.5
  - bioconda::trackhub=0.1.2019.12.24
  - bioconda::pysradb=0.11.1
  - conda-forge::matplotlib=3.3.2
