# complement the configuration
configfile: "config.yaml"


# do onstart/onexit things
sample_schemas = ['sample']
config_schemas = ['general', 'download', 'alignment_general']
include: "../../rules/configuration.smk"


# load all the relevant rules
include: f"{config['rule_dir']}/get_fastq.smk"
include: f"{config['rule_dir']}/merge_replicates.smk"
include: f"{config['rule_dir']}/qc.smk"
include: f"{config['rule_dir']}/trimming.smk"


# set the quality_control functions
quality_control = [get_trimming_qc]


rule scRNA_seq_all:
    """
    TODO: Skeleton scRNA_seq all function
    """
    input:
        expand((["{qc_dir}/multiqc_{assemblies}.html"] if config["create_qc_report"] else []) +
                [f"{{fastq_dir}}/{sample}_{{fqext}}.{{fqsuffix}}.gz" if config['layout'][sample] == "PAIRED" else
                 f"{{fastq_dir}}/{sample}.{{fqsuffix}}.gz" for sample in samples.index],
                **{**config,
                   **{'assemblies': set(samples['assembly']), 'peak_caller': config['peak_caller'].keys()}})
