from snakemake.utils import validate


# complement the configuration
if not 'validated' in config:
    configfile: "config.yaml"
    validate(config, schema=f"../../schemas/config.schema.yaml")

# do onstart/onexit things
schema = 'download_fastq.schema.yaml'
include: f"{config['rule_dir']}/configuration.smk"


# load the relevant rules
include: f"{config['rule_dir']}/get_fastq.smk"


rule download_all:
    """
    download all samples
    """
    input:
        [expand(f"{{result_dir}}/{{fastq_dir}}/{sample}_{{fqext}}.{{fqsuffix}}.gz", **config) if config['layout'][sample] == "PAIRED" else
         expand(f"{{result_dir}}/{{fastq_dir}}/{sample}.{{fqsuffix}}.gz", **config) for sample in samples.index]
