# do onstart/onexit things
sample_schemas = ['sample', 'assembly', 'technical_replicates', 'strandedness']
config_schemas = ['general', 'download', 'alignment_general', 'alignment_specific', 'gene_expression', 'deseq2', 'trackhub']
include: "../../rules/configuration.smk"


# load the remaining relevant rules
include: f"{config['rule_dir']}/alignment.smk"
include: f"{config['rule_dir']}/bam_cleaning.smk"
include: f"{config['rule_dir']}/bigfiles.smk"
include: f"{config['rule_dir']}/deseq2.smk"
include: f"{config['rule_dir']}/gene_counts.smk"
include: f"{config['rule_dir']}/get_genome.smk"
include: f"{config['rule_dir']}/get_fastq.smk"
include: f"{config['rule_dir']}/merge_replicates.smk"
include: f"{config['rule_dir']}/strandedness.smk"
include: f"{config['rule_dir']}/trackhub.smk"
include: f"{config['rule_dir']}/trimming.smk"
include: f"{config['rule_dir']}/quantification.smk"
include: f"{config['rule_dir']}/qc.smk"
include: f"{config['rule_dir']}/qc_rna.smk"


# load the quality control files
quality_control = [get_trimming_qc, get_rna_qc] if config['quantifier'] == 'salmon' and config['create_trackhub'] == False else [get_trimming_qc, get_alignment_qc, get_rna_qc]

rule seq2science:
    """
    count expressed genes per assembly and (optionally) perform differential expression analysis
    """
    input:
         expand(
             (["{trackhub_dir}"]                     if config['create_trackhub']  else []) +
             (["{qc_dir}/multiqc_{assemblies}.html"] if config["create_qc_report"] else []) +

             (["{counts_dir}/{assemblies}-counts.tsv"]) +
             (["{counts_dir}/{assemblies}-DEXSeq_counts.tsv"] if config['dexseq'] else []) +
             (["{genome_dir}/{assemblies}/gene_id2name.tsv"]), assemblies=all_assemblies, **config) +
         DE_contrasts
