# do onstart/onexit things
sample_schemas = ['sample', 'assembly']
config_schemas = ['general', 'download', 'alignment_general', 'alignment_specific', 'trackhub']
include: "../../rules/configuration_generic.smk"
include: "../../rules/configuration_workflows.smk"


# load all the relevant rules
include: f"{config['rule_dir']}/alignment.smk"
include: f"{config['rule_dir']}/bigfiles.smk"
include: f"{config['rule_dir']}/get_fastq.smk"
include: f"{config['rule_dir']}/get_genome.smk"
include: f"{config['rule_dir']}/merge_replicates.smk"
include: f"{config['rule_dir']}/qc.smk"
include: f"{config['rule_dir']}/trackhub.smk"
include: f"{config['rule_dir']}/trimming.smk"
include: f"{config['rule_dir']}/quantification.smk"


# set the quality_control functions
quality_control = [get_trimming_qc, get_alignment_qc]


rule scRNA_seq_all:
    """
    TODO: Skeleton scRNA_seq all function
    """
    input:
        expand([f"{{result_dir}}/{{quantifier}}/{treps.loc[trep, 'assembly']}-{trep}" for trep in treps.index],
               **{**config,
                  **{'assemblies': set(samples['assembly'])}})
