#Input here the plate & plate numbers including the primer plate. e.g. GF_plate1_COL_1&2, GF_plate2_COL_5&6, or nextera for the original nextera index primers.
#If you are unsure from which primer plate your sample originated, dont gues but ask!

[plate.iPSC-2-KC-diff-iPSC-scATAC-16561]
   primer_plate = "nextera"
[plate.iPSC-2-KC-diff-iPSC-293-KC-PKC19-A0004-plate2-16718]
   primer_plate = "nextera"
[plate.iPSC-2-KC-diff-iPSC-293-KC-PKC19-A0004-plate3-16719]
   primer_plate = "nextera"
[plate.iPSC-2-KC-diff-iPSC-293-KC-PKC19-A0004-plate4-16975]
   primer_plate = "nextera"
[plate.iPSC-2-KC-diff-eLSC-and-KC-PKC19-A0005-plate6-17128]
   primer_plate = "nextera"
[plate.iPSC-2-KC-diff-eLSC-and-KC-PKC19-A0005-plate7-17129]
   primer_plate = "nextera"
[plate.scATAC-LSC-LSC-159-17689]
   primer_plate = "GF_plate1_COL_1&2"
[plate.scATAC-LSC-LSC-AN40-17690]
   primer_plate = "GF_plate1_COL_3&4"

#Input here the cell types sorted in each well. For more information on how to imput e.g specific paterns in the plate see "https://bio96.readthedocs.io/en/latest/file_format.html"
[plate.iPSC-2-KC-diff-iPSC-scATAC-16561.row.'A,B,...,P']
[plate.iPSC-2-KC-diff-iPSC-scATAC-16561.col.'1,2,...,24']
  cell_type = "iPSCs"

[plate.iPSC-2-KC-diff-iPSC-293-KC-PKC19-A0004-plate2-16718.row.'A,B,...,P']
[plate.iPSC-2-KC-diff-iPSC-293-KC-PKC19-A0004-plate2-16718.col.'1,2,...,12']
  cell_type = "iPSCs"
[plate.iPSC-2-KC-diff-iPSC-293-KC-PKC19-A0004-plate2-16718.col.'13,14,...,24']
  cell_type = "KCs"

[plate.iPSC-2-KC-diff-iPSC-293-KC-PKC19-A0004-plate3-16719.row.'A,B,...,P']
[plate.iPSC-2-KC-diff-iPSC-293-KC-PKC19-A0004-plate3-16719.col.'1,2,...,12']
  cell_type = "KCs"
[plate.iPSC-2-KC-diff-iPSC-293-KC-PKC19-A0004-plate3-16719.col.'13,14,...,24']
  cell_type = "iPSCs"

[plate.iPSC-2-KC-diff-iPSC-293-KC-PKC19-A0004-plate4-16975.row.'A,B,...,P']
[plate.iPSC-2-KC-diff-iPSC-293-KC-PKC19-A0004-plate4-16975.col.'1,2,...,24']
  cell_type = "KC_frozen"

[plate.iPSC-2-KC-diff-eLSC-and-KC-PKC19-A0005-plate6-17128.row.'A,B,...,P']
[plate.iPSC-2-KC-diff-eLSC-and-KC-PKC19-A0005-plate6-17128.col.'1,2,...,12']
  cell_type = "KCs"
[plate.iPSC-2-KC-diff-eLSC-and-KC-PKC19-A0005-plate6-17128.col.'13,14,...,24']
  cell_type = "LSCs"

[plate.iPSC-2-KC-diff-eLSC-and-KC-PKC19-A0005-plate7-17129.row.'A,B,...,P']
[plate.iPSC-2-KC-diff-eLSC-and-KC-PKC19-A0005-plate7-17129.col.'1,2,...,12']
  cell_type = "LSCs"
[plate.iPSC-2-KC-diff-eLSC-and-KC-PKC19-A0005-plate7-17129.col.'13,14,...,24']
  cell_type = "KCs"
  
[plate.scATAC-LSC-LSC-159-17689.row.'A,B,...,P']
[plate.scATAC-LSC-LSC-159-17689.col.'1,2,...,24']
  cell_type = "LSC_177"

[plate.scATAC-LSC-LSC-AN40-17690.row.'A,B,...,P']
[plate.scATAC-LSC-LSC-AN40-17690.'1,2,...,24']
  cell_type = "LSC_AN40"


