from snakemake.utils import validate


# complement the configuration
if not 'validated' in config:
    configfile: "config.yaml"
    validate(config, schema=f"../../schemas/config.schema.yaml")

# do onstart/onexit things
schema = 'call_peaks.schema.yaml'
include: f"{config['rule_dir']}/configuration.smk"


# load the 'subworkflow' alignment
include: "../alignment/Snakefile"


# load the remaining relevant rules
include: f"{config['rule_dir']}/call_peak.smk"
include: f"{config['rule_dir']}/get_genome.smk"
include: f"{config['rule_dir']}/qc.smk"


if 'condition' in config:
    assert False
#     rule all:
#         """
#         call peaks for each sample, IDR / genrich
#         """
else:
    rule call_peaks_all:
        """
        call peaks for each sample, no IDR / genrich replicates
        """
        input:
            [expand(f"{{result_dir}}/{{peak_caller}}/{sample}-{samples.loc[sample, 'assembly']}_peaks.narrowPeak", **config)
             for sample in samples.index]

