---
title: "analysis-sct.Rmd"
output: pdf_document
---

```{r Perform SCTransform, warning=FALSE}
 ##Perform SCTransform
sct <- SCTransform(seuset, assay = "sf", variable.features.n=params$nhvg, vars.to.regress = vars_to_regress_sf, verbose = FALSE)
```

```{r}
# looking into the dataset
VlnPlot(
    object = sct,
    features = c("nFeature_sf"),
    group.by = params$lab_col
)
VlnPlot(
    object = sct,
    features = c("nCount_sf"),
    group.by = params$lab_col
)
FeatureScatter(
    object = sct,
    feature1 = "nCount_sf",
    feature2 = "nFeature_sf"
)
```

```{r plot SCT normalized counts/features}
# Seurat normalization: "a global-scaling normalization method LogNormalize that
# normalizes the gene expression measurements for each cell by the total
# expression, multiplies this by a scale factor (10,000 by default), and
# log-transforms the result.""
# looking into the dataset
VlnPlot(
    object = sct,
    features = c("nFeature_SCT"),
    group.by = params$lab_col
)
VlnPlot(
    object = sct,
    features = c("nCount_SCT"),
    group.by = params$lab_col
)
FeatureScatter(
    object = sct,
    feature1 = "nCount_SCT",
    feature2 = "nFeature_SCT"
)
saveRDS(seuset, paste(params$resultsdir,"seuset_qc+norm.rds",sep="/"))
```

#### Check confounders before & after normalization

```{r seurat objects to sce}
# Only take the entries that are matchable with the counttable entries:
# Here we take the vst normalized and logp1 transformed counts from the SCT assay (data slot)
filtered_cells <- intersect(rownames(phenodata), 
                            colnames(sct@assays$SCT))
pheno_matchedseuset <- phenodata[filtered_cells, ]
pheno_orderedseuset <-
pheno_matchedseuset[match(colnames(sct@assays$SCT),
rownames(pheno_matchedseuset)), ]
count_matrixseuset <- as.matrix(sct@assays$SCT@data)
sce_seunorm <-
SingleCellExperiment(
assays = list(counts = count_matrixseuset),
colData = pheno_orderedseuset,
rowData = rownames(count_matrixseuset)
)
# A little trick to let scater know that there are actually logcounts in the dataset.
assay(sce_seunorm, "logcounts") <- counts(sce_seunorm)
# Calculate the quality metrics:
sce_seunorm <- calculateQCMetrics(
  sce_seunorm)
```

# Identifying the variation caused by each confounding factor
#### Before & after normalization

```{r check confounders in raw dataset}
explanatory_variables <- as.factor(c(confounders_to_test, 
                                     "total_features_by_counts", "total_counts"))
#explanatory_variables_seu <- c("total_features_by_counts", "total_counts",
#confounders_to_test)
# This function and visualization performs a PCA analysis in the data object and
# checks to what extend the variables that are put in, are explaining the
# variance. The percentage of variance explained by each variable of interest:
# Setting the colours:
colourvector <- c()
colourset <- brewer.pal(length(explanatory_variables),"Dark2")
i <- 1
for (variable_item in explanatory_variables){
  colourvector[variable_item] <- colourset[i]
  i <- i + 1
}
# Building combined plot, before and after normalization
p1 <- plotExplanatoryVariables(sce_endo,
                               exprs_values = "counts",
                               variables = explanatory_variables) + 
                               expand_limits(y = 1) + 
                               scale_color_manual(values = colourvector) + 
                               ggtitle("Explanatory Variables Before Normalization")
p2 <- plotExplanatoryVariables(sce_seunorm,
                               variables = explanatory_variables) + 
                               expand_limits(y = 1) + 
                               scale_color_manual(values = colourvector) + 
                               ggtitle("Explanatory Variables After Normalization")
multiplot(p1, p2)
```


```{r  running PCA on SCT normalized counts}
sce_seunorm <- runPCA(
  sce_seunorm, ncomponents = 20,
  exprs_values = "counts"
)
```


```{r PCA plot after SCT normalization,  linewidth=60}
# plotting again the PCA's on raw-transformed and normalized values
# raw log-transformation.
#tmp <- runPCA(sce_endo, ncomponents = 50, exprs_values = "logcounts_raw")
# PCA plot after log2 transformation
# plotPCA(tmp,
#         colour_by = params$lab_col,
#         size_by = "total_features_by_counts")
# PCA plot after seurat normalization
plotPCA(sce_seunorm,
        colour_by = params$lab_col,
        size_by = "total_features_by_counts")
```
## Highly variable genes & Scaling of the gene expression values
```{r print VariableFeatures SCTransform}
# FindVariableFeatures plots the dispersion (= a normalized measure of
# cell-to-cell variation), as a function of average expression for each gene. In
# their tutorial the Satija lab uses the cut-off of 2000 genes.
# top 10 most variable genes
top20 <- head(VariableFeatures(sct, assay = "SCT"), 20)
# plot variable features with labels:
plot1 <- VariableFeaturePlot(sct, assay="SCT")
plot2 <- LabelPoints(plot = plot1, points = top20, repel = TRUE)
plot2
# Preferable removing the genes that are highly expressed but with a low variance.
length(x = sct@assays$SCT@var.features)
#seu[["sf"]]@var.features[1:10]
```

```{r scaling and regressing,  linewidth=60}
# Scaling the data to make it usable for dimensional reduction
# using all the genes, could also select only the highly variable genes.
# Optional regression is performed here.
all.genes <- rownames(seuset)
```

## Running PCA analysis on the scaled data
```{r running PCA}
#seuset <- seu
#rm(seu)
#DefaultAssay(seuset) <- "sf"
seuset <- RunPCA(
    object = sct,
    features = VariableFeatures(object = sct),
    npcs = params$pcs_max_hvg,
    ndims.print = 1:5,
    nfeatures.print = 5
)
length(sct@assays$SCT@var.features)
```