# do onstart/onexit things
SAMPLE_SCHEMAS = ['sample']
CONFIG_SCHEMAS = ['general', 'download']
include: "../../rules/configuration.smk"


# load the relevant rules
include: f"{config['rule_dir']}/get_fastq.smk"


rule seq2science:
    """
    download all samples
    """
    input:
        [expand(f"{{fastq_dir}}/{sample}_{{fqext}}.{{fqsuffix}}.gz", **config) if SAMPLEDICT[sample]['layout'] == "PAIRED" else
         expand(f"{{fastq_dir}}/{sample}.{{fqsuffix}}.gz", **config) for sample in samples.index]
