from snakemake.utils import validate


# complement the configuration
if not 'validated' in config:
    configfile: "config.yaml"
    validate(config, schema=f"../../schemas/config.schema.yaml")

# do onstart/onexit things
schema = 'alignment.schema.yaml'
include: f"{config['rule_dir']}/configuration.smk"


# load the 'subworkflow' download_fastq
include: "../download_fastq/Snakefile"


# load the remaining relevant rules
include: f"{config['rule_dir']}/get_genome.smk"
include: f"{config['rule_dir']}/alignment.smk"
include: f"{config['rule_dir']}/trim_auto.smk"


rule align_all:
    """
    align each sample against its assembly
    """
    input:
        [expand(f"{{result_dir}}/{{bwa_dir}}/{sample}-{samples.loc[sample]['assembly']}.bam", **config) for sample in samples.index],
        [expand(f"{{result_dir}}/{{bwa_dir}}/{sample}-{samples.loc[sample]['assembly']}.bai", **config) for sample in samples.index]
